### ISSUE TITLE
line comment does not work in online interpreter

### ISSUE THREAD

**Issue by stasoid** [presidentbeef/brat#13]
In [online interpreter](http://try.brat-lang.org/#) this code does not work:
```
#;+
p "hi"
```

**Comment by presidentbeef** [comment]
Ah, interesting. This is because it's parsing `;` as an end-of-line character and `+` is then on the next line.

**Comment by stasoid** [comment]
Looks like this change in `parser.peg` will fix the issue (I didn't test it though). 
Changed `eol` to `"\n"` (no need to specify `| "\r\n"` here, it already handles both line endings properly).

```
comment = opt_space "#*" (!"*#" (comment | .))* ("*#" | eof)
        | opt_space "#" (!("\n" | eof) .)*
```

This rule has another problem: `#` comments out `*#`, so this will not work:
```
#*
#lala*#
p "hi"
```

If this behavior was not intended this may be appropriate fix for it (again, I didn't test it):

```
block_comment = opt_space "#*" (!"*#" (block_comment | .))* ("*#" | eof)

comment = block_comment
        | opt_space "#" (!("\n" | eof) .)*
```

Also I want to say that some grammar rules are a bit confusing. For example, `eof` surprisingly is not just `!.`. 
This leads to undesirable effects in other parts of the grammar. For example, by reading the `comment` rule one may conclude that block comment is allowed not to be closed at the end of file: `("*#" | eof)`. But this is actually not true because `eof` rule always consumes and after `(!"*#" (comment | .))*` there are no characters to consume, so `eof` always fails (even at the end of file!).

**Comment by presidentbeef** [comment]
Thanks for the feedback, I'll take a look at those proposed changes.

> Also I want to say that some grammar rules are a bit confusing.

Yeah.

> For example, by reading the comment rule one may conclude that block comment is allowed not to be closed at the end of file

Yes, that *is* true...

> But this is actually not true because eof rule always consumes

I don't follow...

```
eof     = (eol | space)? !.
```

The `eof` rule doesn't have to consume anything. It optionally consumes spaces at the end of the file and `!.` does not consume anything.

> eof always fails (even at the end of file!).

This doesn't seem possible, but you stated it so confidently that I had to check by removing the `eof` rule entirely. Surprisingly, most programs do parse fine without it. But that is just because most files are going to end with `\n` and the `line` rule will match that. If the file does not end in a newline, though, it will not parse without the `eof` rule.

Also, unterminated block comments `#*` do not work properly without the `eof` rule.

So, I think `eof` does work :)

**Comment by stasoid** [comment]
Sorry, my bad. `eof` indeed does not have to consume anything, I confused `?` with `+`. But then I don't understand why unterminated block comment does not work in online interpreter. This program fails:
```
p "hi"
#*
```

**Comment by presidentbeef** [comment]
That happens to not work because of how the online interpreter was set up. But it should work fine now! Happy 2018 :tada:

**Comment by stasoid** [comment]
Thank you

**Comment by stasoid** [comment]
I am interested in comments fixed because I want to add Brat to [this polyglot](https://codegolf.stackexchange.com/questions/102370/add-a-language-to-a-polyglot?page=6&answertab=oldest). First two lines have several `;` and it is very hard to change the first line of the polyglot, so I cannot work around this bug.

I tried to see how the proposed changes will affect Brat behavior, but could not figure out how to update parser after I changed `parser.peg`. `build.sh` does not automatically apply the changes and running `redo_parser.brat` gives `Method error: null has no method called 'match'.` What should I do to update the parser?

**Comment by presidentbeef** [comment]
You have to run from the root of the project:

`./brat stdlib/parser/utils/redo_parser.brat`

**Comment by stasoid** [comment]
Thank you, that worked. Proposed changes seem to work fine, I created pull request.

**Comment by stasoid** [comment]
Currently line comment can hide end of block comment. Is it intended behavior or not?
In other words, should these programs print `hi`?:
```
#*
#lala *#
p "hi"
```
```
#* #lala *#
p "hi"
```

**Comment by presidentbeef** [comment]
It's not intended behavior.

**Comment by stasoid** [comment]
Ok, good.
