### ISSUE TITLE
Parsing of function literals with argument lists in comma-lists

### ISSUE THREAD

**Issue by catb0t** [presidentbeef/brat#24]
Sorry for so many issues; I really like Brat.

I was interested in extending `true?`, `null?` etc so they give the condition argument to their true/false branches, so that `true? 4 { x | p x }` would print 4.  I have added the feature: https://github.com/catb0t/brat/commit/65fc9ddf04d2f6165fea9226a72eb7172b68b7dd

However, I think have found a parser bug with literals and functions in argument lists.  There is no combination of parentheses and commas that allows this to parse correctly; there is always a name error for `x`: 

```lua 
true? 4 { x | x }
```

However these give `4`: 
```lua
true? 4 { 4 }
f = { x | x }
true? 4 ->f
```

Similarly, this gives `true` (which is not the condition):
```lua
null? null { x | x } { x | x } 
```
I understand that probably parses as `null?(null({ x | x }({x | x})))`, but adding commas like so is also a name error
```lua
null? null, { x | x }, { x | x } # x is not declared
```
Again, it can be worked around by not using a literal:
```lua 
f = { x | x } 
null? null, ->f, ->f # => null
```

In some cases even `->f` doesn't help; if `f` is undeclared then `false? 4, 0, ->f` (or any comma combination of that) will do nothing but wait for a keypress in interactive mode.

If f is declared: 
```lua 
f = {x | x}
false? 4, 0, ->f
#=> Argument error: function expected 1 argument(s) but was given 0.
```
But this is a problem with the way `0, ->f` is parsed, because `false?` definitely gives the condition to the function branch.

**Comment by presidentbeef** [comment]
> Sorry for so many issues; I really like Brat

No need to apologize!

> I was interested in extending true?, null? etc so they give the condition argument to their true/false branches

I like this idea!

I don't have time to look in depth right now, but I believe you are running into another optimization issue. For better performance, Brat will convert some calls to `true?`/`false?`/`null?` directly to `if` expressions in the resulting Lua code.

My guess is that code needs to be modified to support this case. It's really hairy code but it starts around https://github.com/presidentbeef/brat/blob/40b6ff9e97f18555c47f62dd695b995b2ebe6f40/stdlib/parser/invoke_helper.brat#L426

**Comment by presidentbeef** [comment]
@catb0t Can you try #25 with your changes?

**Comment by catb0t** [comment]
It works perfectly, thanks!

**Comment by presidentbeef** [comment]
@catb0t Yes, please!
