### ISSUE TITLE
String interpolation in interactive mode

### ISSUE THREAD

**Issue by andrewnc** [presidentbeef/brat#29]
This may be intended behaviour, but the string interpolation `"#{value}"` functionality doesn't seem to work in the `interactive` repl. 

```
# Interactive Brat
brat:1> a = 1
#=> 1
brat:2> p "#{a}"
#=> [string "interactive"]:12: attempt to index global '_table' (a nil value)
```

This does, however, work if you create a file and run `brat my_file.brat`.

**Comment by presidentbeef** [comment]
Definitely not intentional. Fixed on master.

Thanks!
